name: Manual Trigger Workflow
on:
  workflow_run:
    workflows: [Build]
    types: [requested]
    branches: [dev]
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "sss"
        run: |
          echo "Hello"
