name: "Action Sample"
env:
  AppName: "sample"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        default: "dev"
        required: false
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello"
  
